null pointer exception for this.connection
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.createStatement()" because "this.connection" is null